generation_config:
    max_new_token: 256
    min_new_token: 64
    temperature: 1.0
    top_k: 20
    top_p: 0.0

datapath: "knkarthick/dialogsum"
checkpoint: "google/flan-t5-base"

training_args:
    output_dir: "flant5-fine-tune-running-v0"
    overwrite_output_dir: False
    num_train_epochs: 3
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    weight_decay: 0.005
    evaluation_strategy: "epoch"
    logging_strategy: "steps"
    logging_steps: 1000